In [2]:
%load_ext autoreload
%autoreload 2

from src.preprocessing import *
import src.ocp as ocp

from src.trading import *

from pathlib import Path
import polars as pl
import numpy as np

In [3]:
#1) Get selected tickers
tickers = get_selected_tickers()

# 2) Load per-ticker returns
frames = load_selected_ticker_frames()

2026-01-21 15:31:31,435 | INFO | Found 91 selected tickers.
2026-01-21 15:31:32,266 | INFO | Loaded 90 selected ticker frames into memory.

In [4]:
DATA_DIR = Path("data/selected/SP100/bbo")
TICKERS = tickers

daily_matrices = ocp.build_daily_return_matrices(
    data_dir=DATA_DIR,
    ticker_list=TICKERS,
    return_col="mid_price_return"
)

print(f"Built {len(daily_matrices)} daily return matrices.")

daily_pairs = ocp.build_daily_pairs(daily_matrices)

Built 565 daily return matrices.

In [5]:
daily_matrices

{datetime.date(2015, 1, 2):                             AAPL.OQ     ABT.N     ACN.N     AIG.N     ALL.N  \
 timestamp
 2015-01-02 09:32:00-05:00  0.000404 -0.000443  0.000000 -0.000796 -0.001696
 2015-01-02 09:33:00-05:00 -0.000045 -0.000775  0.000335 -0.000266  0.000991
 2015-01-02 09:34:00-05:00 -0.001033  0.002881  0.001450  0.001772  0.002122
 2015-01-02 09:35:00-05:00 -0.001124 -0.000331  0.001782 -0.001238  0.000565
 2015-01-02 09:36:00-05:00  0.001531  0.003427  0.000056 -0.003276 -0.002187
 ...                             ...       ...       ...       ...       ...
 2015-01-02 15:56:00-05:00 -0.000274  0.000000 -0.000056  0.000534  0.000214
 2015-01-02 15:57:00-05:00  0.000183  0.000334 -0.000561  0.000000  0.000143
 2015-01-02 15:58:00-05:00 -0.001188 -0.000556 -0.001123 -0.000979 -0.001070
 2015-01-02 15:59:00-05:00  0.000183  0.000445 -0.000112  0.000089  0.000500
 2015-01-02 16:00:00-05:00  0.000137 -0.001112 -0.000900 -0.000356  0.000071

                             AMGN.OQ     AXP.N      BA.N     BAC.N   BIIB.OQ  \
 timestamp
 2015-01-02 09:32:00-05:00  0.000187  0.000000 -0.000152 -0.000832  0.000073
 2015-01-02 09:33:00-05:00  0.000498  0.001498 -0.000076  0.000000  0.003705
 2015-01-02 09:34:00-05:00  0.004046  0.000855  0.001106 -0.000555  0.002180
 2015-01-02 09:35:00-05:00  0.000248 -0.000427  0.000876 -0.002222  0.004828
 2015-01-02 09:36:00-05:00  0.004896 -0.000908  0.001332 -0.000557 -0.000447
 ...                             ...       ...       ...       ...       ...
 2015-01-02 15:56:00-05:00 -0.000718  0.000107  0.000346  0.000000 -0.000905
 2015-01-02 15:57:00-05:00  0.000781 -0.000322 -0.000077  0.000000  0.000380
 2015-01-02 15:58:00-05:00 -0.001093 -0.001181 -0.000308 -0.000558 -0.000540
 2015-01-02 15:59:00-05:00  0.000406  0.000215  0.000115 -0.000558  0.000219
 2015-01-02 16:00:00-05:00 -0.001406 -0.000054 -0.000269 -0.000559 -0.001300

                            ...     TWX.N     UNH.N     UNP.N     UPS.N  \
 timestamp                  ...
 2015-01-02 09:32:00-05:00  ...  0.003722 -0.001178  0.000000 -0.000270
 2015-01-02 09:33:00-05:00  ...  0.002086 -0.001081  0.001288  0.002699
 2015-01-02 09:34:00-05:00  ...  0.000752  0.001673  0.001161 -0.000583
 2015-01-02 09:35:00-05:00  ...  0.000116  0.002947 -0.004392 -0.000359
 2015-01-02 09:36:00-05:00  ...  0.000866  0.003085  0.002996  0.000180
 ...                        ...       ...       ...       ...       ...
 2015-01-02 15:56:00-05:00  ...  0.000000  0.000149  0.000463  0.000181
 2015-01-02 15:57:00-05:00  ...  0.000059  0.000396  0.000168  0.000045
 2015-01-02 15:58:00-05:00  ... -0.000999 -0.001090 -0.001304 -0.000860
 2015-01-02 15:59:00-05:00  ...  0.000000 -0.000099  0.000337  0.000408
 2015-01-02 16:00:00-05:00  ... -0.000647 -0.000496 -0.001011 -0.000769

                               USB.N     UTX.N       V.N      VZ.N     WFC.N  \
 timestamp
 2015-01-02 09:32:00-05:00  0.000111 -0.000130  0.004842 -0.000425  0.000091
 2015-01-02 09:33:00-05:00  0.002766  0.000520 -0.002202  0.000638  0.002364
 2015-01-02 09:34:00-05:00 -0.001324  0.000607 -0.000170  0.000744 -0.001361
 2015-01-02 09:35:00-05:00 -0.000221 -0.002641  0.002623 -0.001275  0.000182
 2015-01-02 09:36:00-05:00 -0.001657  0.000695  0.001280  0.000319  0.000454
 ...                             ...       ...       ...       ...       ...
 2015-01-02 15:56:00-05:00  0.000223  0.000217  0.000528 -0.000213 -0.000183
 2015-01-02 15:57:00-05:00  0.000000 -0.000304  0.000170 -0.000213  0.000183
 2015-01-02 15:58:00-05:00 -0.000891 -0.000738 -0.000660 -0.000638 -0.001095
 2015-01-02 15:59:00-05:00 -0.000223  0.000217  0.000207  0.000213  0.000000
 2015-01-02 16:00:00-05:00 -0.000223 -0.000782 -0.001094 -0.000426 -0.000548

                               WMT.N
 timestamp
 2015-01-02 09:32:00-05:00 -0.000058
 2015-01-02 09:33:00-05:00  0.000581
 2015-01-02 09:34:00-05:00  0.000000
 2015-01-02 09:35:00-05:00  0.000174
 2015-01-02 09:36:00-05:00  0.002552
 ...                             ...
 2015-01-02 15:56:00-05:00  0.000291
 2015-01-02 15:57:00-05:00  0.000000
 2015-01-02 15:58:00-05:00 -0.000930
 2015-01-02 15:59:00-05:00  0.000466
 2015-01-02 16:00:00-05:00 -0.000465

 [389 rows x 91 columns],
 datetime.date(2015, 1, 5):                             AAPL.OQ     ABT.N     ACN.N     AIG.N     ALL.N  \
 timestamp
 2015-01-05 09:32:00-05:00  0.002871 -0.000224  0.000000 -0.000899 -0.000072
 2015-01-05 09:33:00-05:00 -0.001709  0.001568 -0.000510  0.000719  0.000144
 2015-01-05 09:34:00-05:00  0.002220  0.002012 -0.000340  0.001438 -0.000287
 2015-01-05 09:35:00-05:00  0.002123 -0.000558  0.001475  0.002244  0.000933
 2015-01-05 09:36:00-05:00 -0.000092  0.000000 -0.000113 -0.000895 -0.000717
 ...                             ...       ...       ...       ...       ...
 2015-01-05 15:56:00-05:00  0.000893 -0.000444 -0.000171  0.000363 -0.000145
 2015-01-05 15:57:00-05:00  0.000188 -0.000222 -0.000171 -0.000181  0.000290
 2015-01-05 15:58:00-05:00 -0.000939 -0.001110 -0.001599 -0.001361 -0.001523
 2015-01-05 15:59:00-05:00 -0.000752 -0.000667 -0.000686 -0.000545 -0.001380
 2015-01-05 16:00:00-05:00 -0.000470 -0.000334  0.000458 -0.000091 -0.000291

                             AMGN.OQ     AXP.N      BA.N     BAC.N   BIIB.OQ  \
 timestamp
 2015-01-05 09:32:00-05:00  0.000634  0.000974  0.000000 -0.003376  0.001858
 2015-01-05 09:33:00-05:00 -0.000158  0.000108  0.000000  0.002258  0.000088
 2015-01-05 09:34:00-05:00 -0.000983  0.000702  0.003751  0.000000 -0.000324
 2015-01-05 09:35:00-05:00 -0.001047  0.001242 -0.001387  0.002816  0.000412
 2015-01-05 09:36:00-05:00 -0.001811 -0.000647  0.000309 -0.002247 -0.003958
 ...                             ...       ...       ...       ...       ...
 2015-01-05 15:56:00-05:00  0.000063  0.000220  0.000580  0.000000  0.000089
 2015-01-05 15:57:00-05:00 -0.000315 -0.000550 -0.000464  0.000000 -0.000237
 2015-01-05 15:58:00-05:00 -0.001640 -0.001211 -0.001083 -0.001720 -0.001614
 2015-01-05 15:59:00-05:00 -0.000379 -0.000882 -0.000968 -0.001148 -0.000697
 2015-01-05 16:00:00-05:00 -0.001201 -0.000552 -0.000039 -0.000575 -0.000371

                            ...     TWX.N     UNH.N     UNP.N     UPS.N  \
 timestamp                  ...
 2015-01-05 09:32:00-05:00  ... -0.001656 -0.001647 -0.005213 -0.002003
 2015-01-05 09:33:00-05:00  ... -0.000533 -0.001650  0.000213 -0.001414
 2015-01-05 09:34:00-05:00  ... -0.000296  0.002404 -0.000128  0.000776
 2015-01-05 09:35:00-05:00  ... -0.000712  0.000949  0.000170  0.000274
 2015-01-05 09:36:00-05:00  ...  0.000534  0.000300  0.004259  0.000912
 ...                        ...       ...       ...       ...       ...
 2015-01-05 15:56:00-05:00  ...  0.000000 -0.000302  0.000000  0.000323
 2015-01-05 15:57:00-05:00  ... -0.000299 -0.000302  0.000000 -0.000184
 2015-01-05 15:58:00-05:00  ... -0.001257 -0.001561 -0.001957 -0.001060
 2015-01-05 15:59:00-05:00  ... -0.001139 -0.000555 -0.000392 -0.000969
 2015-01-05 16:00:00-05:00  ... -0.000240  0.000404 -0.000697 -0.000600

                               USB.N     UTX.N       V.N      VZ.N     WFC.N  \
 timestamp
 2015-01-05 09:32:00-05:00 -0.002463 -0.002392  0.000000 -0.000852 -0.002951
 2015-01-05 09:33:00-05:00  0.002693  0.001962 -0.001614  0.001279  0.002960
 2015-01-05 09:34:00-05:00  0.000224  0.002698  0.000818 -0.000319  0.000092
 2015-01-05 09:35:00-05:00  0.001678  0.001041 -0.000171 -0.001703  0.001660
 2015-01-05 09:36:00-05:00 -0.001452  0.000477 -0.000095 -0.000533 -0.000737
 ...                             ...       ...       ...       ...       ...
 2015-01-05 15:56:00-05:00  0.000000  0.000176 -0.000154  0.000214  0.000000
 2015-01-05 15:57:00-05:00  0.000228 -0.000397 -0.000365  0.000000  0.000187
 2015-01-05 15:58:00-05:00 -0.001367 -0.001411 -0.001327 -0.001071 -0.001311
 2015-01-05 15:59:00-05:00 -0.001141 -0.000751 -0.000655 -0.000751 -0.001875
 2015-01-05 16:00:00-05:00 -0.000457  0.000044  0.000366 -0.000107 -0.000188

                               WMT.N
 timestamp
 2015-01-05 09:32:00-05:00  0.000000
 2015-01-05 09:33:00-05:00  0.001048
 2015-01-05 09:34:00-05:00 -0.000756
 2015-01-05 09:35:00-05:00 -0.000582
 2015-01-05 09:36:00-05:00 -0.000116
 ...                             ...
 2015-01-05 15:56:00-05:00 -0.000407
 2015-01-05 15:57:00-05:00 -0.000291
 2015-01-05 15:58:00-05:00 -0.000757
 2015-01-05 15:59:00-05:00 -0.000758
 2015-01-05 16:00:00-05:00 -0.000642

 [389 rows x 91 columns],
 datetime.date(2015, 1, 6):                             AAPL.OQ     ABT.N     ACN.N     AIG.N     ALL.N  \
 timestamp
 2015-01-06 09:32:00-05:00 -0.001269 -0.000668  0.000000  0.000091 -0.000145
 2015-01-06 09:33:00-05:00  0.001506  0.001336 -0.000057 -0.002285 -0.000362
 2015-01-06 09:34:00-05:00  0.001785 -0.001445  0.001720 -0.000458  0.000580
 2015-01-06 09:35:00-05:00 -0.000657 -0.000445  0.000057 -0.001008 -0.000579
 2015-01-06 09:36:00-05:00 -0.001596  0.002005  0.000229 -0.000275  0.001087
 ...                             ...       ...       ...       ...       ...
 2015-01-06 15:56:00-05:00 -0.002346 -0.000899 -0.001494 -0.000830 -0.001090
 2015-01-06 15:57:00-05:00 -0.001975 -0.000225 -0.001324 -0.000461 -0.001018
 2015-01-06 15:58:00-05:00  0.001602  0.000000  0.000749  0.000738  0.000364
 2015-01-06 15:59:00-05:00 -0.000659  0.000000 -0.000346 -0.000184 -0.000218
 2015-01-06 16:00:00-05:00  0.000424 -0.001349 -0.001152 -0.000184 -0.000364

                             AMGN.OQ     AXP.N      BA.N     BAC.N   BIIB.OQ  \
 timestamp
 2015-01-06 09:32:00-05:00 -0.000601 -0.001101 -0.000194  0.000000 -0.000264
 2015-01-06 09:33:00-05:00 -0.000127  0.000386 -0.000388  0.000000  0.004686
 2015-01-06 09:34:00-05:00 -0.000475 -0.001377  0.002133  0.001155  0.004518
 2015-01-06 09:35:00-05:00 -0.001393  0.001655 -0.000774  0.000000 -0.003304
 2015-01-06 09:36:00-05:00 -0.001078 -0.000386  0.000658 -0.002307 -0.000248
 ...                             ...       ...       ...       ...       ...
 2015-01-06 15:56:00-05:00 -0.001560 -0.001688 -0.001017 -0.001182 -0.001530
 2015-01-06 15:57:00-05:00 -0.002832 -0.001184 -0.001214 -0.001184 -0.002544
 2015-01-06 15:58:00-05:00  0.000490  0.000677  0.000667 -0.000593  0.000194
 2015-01-06 15:59:00-05:00 -0.001175 -0.000338  0.000549 -0.000593 -0.000865
 2015-01-06 16:00:00-05:00 -0.001111 -0.000338 -0.001018  0.000000 -0.000299

                            ...     TWX.N     UNH.N     UNP.N     UPS.N  \
 timestamp                  ...
 2015-01-06 09:32:00-05:00  ...  0.000360  0.000852  0.000000  0.000000
 2015-01-06 09:33:00-05:00  ...  0.000720  0.000601 -0.000088  0.000000
 2015-01-06 09:34:00-05:00  ... -0.000479 -0.000150 -0.001936 -0.000506
 2015-01-06 09:35:00-05:00  ...  0.000060  0.000050  0.001587 -0.001243
 2015-01-06 09:36:00-05:00  ... -0.000180 -0.001452  0.001981  0.001199
 ...                        ...       ...       ...       ...       ...
 2015-01-06 15:56:00-05:00  ... -0.001150 -0.001513 -0.001378 -0.001440
 2015-01-06 15:57:00-05:00  ... -0.001455 -0.000858 -0.001157 -0.000791
 2015-01-06 15:58:00-05:00  ... -0.000303  0.000152 -0.000134  0.000465
 2015-01-06 15:59:00-05:00  ... -0.000364 -0.000303  0.000223 -0.000093
 2015-01-06 16:00:00-05:00  ... -0.000243 -0.000202 -0.000178 -0.000372

                               USB.N     UTX.N       V.N      VZ.N     WFC.N  \
 timestamp
 2015-01-06 09:32:00-05:00 -0.001367  0.000400  0.000000  0.001926 -0.002998
 2015-01-06 09:33:00-05:00 -0.001141 -0.000845  0.000077  0.000000 -0.000658
 2015-01-06 09:34:00-05:00  0.000457  0.000000  0.000328 -0.002029 -0.000282
 2015-01-06 09:35:00-05:00  0.000799  0.000890  0.000135  0.000000  0.000188
 2015-01-06 09:36:00-05:00 -0.001597  0.001112  0.000328  0.002997 -0.001505
 ...                             ...       ...       ...       ...       ...
 2015-01-06 15:56:00-05:00 -0.001155 -0.001432 -0.000486 -0.000425 -0.001149
 2015-01-06 15:57:00-05:00 -0.001157 -0.000806 -0.000253  0.000000 -0.000767
 2015-01-06 15:58:00-05:00  0.000463  0.000538  0.000486  0.000000  0.000000
 2015-01-06 15:59:00-05:00 -0.000232  0.000224 -0.000369  0.000000 -0.000576
 2015-01-06 16:00:00-05:00 -0.000695 -0.000851  0.000233 -0.000425 -0.000576

                               WMT.N
 timestamp
 2015-01-06 09:32:00-05:00 -0.000873
 2015-01-06 09:33:00-05:00 -0.000116
 2015-01-06 09:34:00-05:00  0.000116
 2015-01-06 09:35:00-05:00  0.001921
 2015-01-06 09:36:00-05:00  0.002150
 ...                             ...
 2015-01-06 15:56:00-05:00 -0.000925
 2015-01-06 15:57:00-05:00 -0.000694
 2015-01-06 15:58:00-05:00  0.000232
 2015-01-06 15:59:00-05:00  0.000174
 2015-01-06 16:00:00-05:00 -0.000984

 [389 rows x 91 columns],
 datetime.date(2015, 1, 7):                             AAPL.OQ     ABT.N     ACN.N     AIG.N     ALL.N  \
 timestamp
 2015-01-07 09:32:00-05:00 -0.001586  0.000000 -0.000286  0.001011  0.001371
 2015-01-07 09:33:00-05:00 -0.000747 -0.001899 -0.000515 -0.000459 -0.001729
 2015-01-07 09:34:00-05:00 -0.001963 -0.000448 -0.000516 -0.000092 -0.000144
 2015-01-07 09:35:00-05:00  0.003794  0.000224  0.000573  0.000735  0.000505
 2015-01-07 09:36:00-05:00  0.000000  0.001903  0.001891  0.000184  0.000721
 ...                             ...       ...       ...       ...       ...
 2015-01-07 15:56:00-05:00  0.000232  0.000000 -0.000565  0.000000  0.000430
 2015-01-07 15:57:00-05:00  0.000232  0.000224  0.000000  0.000184  0.000430
 2015-01-07 15:58:00-05:00  0.000278  0.000447  0.000113  0.000275  0.000358
 2015-01-07 15:59:00-05:00 -0.000742  0.000000  0.000000  0.000092  0.000286
 2015-01-07 16:00:00-05:00  0.000279  0.000447  0.000226 -0.000184  0.000072

                             AMGN.OQ     AXP.N      BA.N     BAC.N  \
 timestamp
 2015-01-07 09:32:00-05:00 -0.000614  0.000000  0.000813  0.000000
 2015-01-07 09:33:00-05:00 -0.000971  0.000000  0.001471 -0.000878
 2015-01-07 09:34:00-05:00 -0.003401 -0.004867 -0.000464  0.001758
 2015-01-07 09:35:00-05:00 -0.002600  0.000778  0.000387  0.001170
 2015-01-07 09:36:00-05:00 -0.000847 -0.001222 -0.001082  0.001461
 ...                             ...       ...       ...       ...
 2015-01-07 15:56:00-05:00  0.000063  0.000444 -0.000193  0.000000
 2015-01-07 15:57:00-05:00  0.000475  0.000499  0.000039  0.000000
 2015-01-07 15:58:00-05:00  0.001045 -0.000055  0.000502  0.001181
 2015-01-07 15:59:00-05:00 -0.000474  0.000222  0.000154 -0.000590
 2015-01-07 16:00:00-05:00  0.001645 -0.000277 -0.000154  0.000000

                                 BIIB.OQ  ...     TWX.N     UNH.N     UNP.N  \
 timestamp                                ...
 2015-01-07 09:32:00-05:00  3.699119e-03  ... -0.002843 -0.000202  0.002788
 2015-01-07 09:33:00-05:00  2.936642e-05  ... -0.003761  0.001412 -0.000132
 2015-01-07 09:34:00-05:00 -1.669239e-16  ...  0.004202 -0.001057 -0.003487
 2015-01-07 09:35:00-05:00  1.482961e-03  ...  0.000849  0.001613  0.001373
 2015-01-07 09:36:00-05:00  5.864415e-05  ...  0.001697  0.001359 -0.003539
 ...                                 ...  ...       ...       ...       ...
 2015-01-07 15:56:00-05:00 -5.817336e-04  ...  0.000301  0.000301  0.000177
 2015-01-07 15:57:00-05:00  1.845595e-04  ... -0.000301  0.000451  0.000177
 2015-01-07 15:58:00-05:00  7.948787e-04  ...  0.000843  0.000451  0.000442
 2015-01-07 15:59:00-05:00  1.177188e-03  ...  0.000181  0.000150  0.000000
 2015-01-07 16:00:00-05:00  1.175804e-03  ...  0.000963 -0.000050 -0.002034

                               UPS.N     USB.N     UTX.N       V.N      VZ.N  \
 timestamp
 2015-01-07 09:32:00-05:00  0.000000 -0.000345  0.000713  0.000000 -0.000852
 2015-01-07 09:33:00-05:00  0.000000 -0.000345  0.001603  0.001007 -0.002772
 2015-01-07 09:34:00-05:00  0.000000  0.000460  0.001022  0.000696  0.000214
 2015-01-07 09:35:00-05:00  0.000464  0.001608  0.000400 -0.000232 -0.000214
 2015-01-07 09:36:00-05:00 -0.000325 -0.001032 -0.000755  0.001701  0.000107
 ...                             ...       ...       ...       ...       ...
 2015-01-07 15:56:00-05:00  0.000046  0.000230  0.000355  0.000173  0.000867
 2015-01-07 15:57:00-05:00  0.000277  0.000230 -0.000089  0.000537  0.000216
 2015-01-07 15:58:00-05:00  0.000461  0.000000  0.000532  0.000460 -0.000108
 2015-01-07 15:59:00-05:00  0.000369  0.000460 -0.000222 -0.000326  0.000541
 2015-01-07 16:00:00-05:00 -0.000138  0.000000 -0.000044 -0.000690 -0.000865

                               WFC.N     WMT.N
 timestamp
 2015-01-07 09:32:00-05:00 -0.001524  0.003052
 2015-01-07 09:33:00-05:00  0.000000 -0.000287
 2015-01-07 09:34:00-05:00  0.000763 -0.000287
 2015-01-07 09:35:00-05:00  0.000572  0.001838
 2015-01-07 09:36:00-05:00 -0.000190  0.001376
 ...                             ...       ...
 2015-01-07 15:56:00-05:00  0.000000  0.000339
 2015-01-07 15:57:00-05:00  0.000382  0.000056
 2015-01-07 15:58:00-05:00  0.000095  0.000395
 2015-01-07 15:59:00-05:00 -0.000095 -0.000113
 2015-01-07 16:00:00-05:00 -0.000477 -0.000338

 [389 rows x 91 columns],
 datetime.date(2015, 1, 8):                             AAPL.OQ     ABT.N     ACN.N         AIG.N  \
 timestamp
 2015-01-08 09:32:00-05:00  0.001424  0.002548  0.000000  0.000000e+00
 2015-01-08 09:33:00-05:00 -0.001284  0.002210  0.000000 -1.744880e-03
 2015-01-08 09:34:00-05:00 -0.000046  0.001544  0.000000  1.307346e-16
 2015-01-08 09:35:00-05:00  0.001561 -0.000440  0.001686  1.195952e-03
 2015-01-08 09:36:00-05:00 -0.000092  0.002203 -0.000337  9.188643e-05
 ...                             ...       ...       ...           ...
 2015-01-08 15:56:00-05:00 -0.000715 -0.000219 -0.000556 -5.537610e-04
 2015-01-08 15:57:00-05:00 -0.000089  0.001096  0.000557  1.108136e-03
 2015-01-08 15:58:00-05:00 -0.000358  0.000000  0.000111  0.000000e+00
 2015-01-08 15:59:00-05:00  0.000000  0.000000 -0.000056  1.844848e-04
 2015-01-08 16:00:00-05:00  0.000805  0.000000  0.000278  3.689016e-04

                               ALL.N   AMGN.OQ     AXP.N      BA.N     BAC.N  \
 timestamp
 2015-01-08 09:32:00-05:00  0.000781  0.007530 -0.000219  0.001684  0.000583
 2015-01-08 09:33:00-05:00  0.000355 -0.000772 -0.001095  0.000955 -0.001164
 2015-01-08 09:34:00-05:00  0.000284  0.004358  0.000931  0.001145 -0.002040
 2015-01-08 09:35:00-05:00  0.001277 -0.000923 -0.000438 -0.001411  0.001460
 2015-01-08 09:36:00-05:00 -0.000992 -0.004621 -0.001424  0.000649 -0.002333
 ...                             ...       ...       ...       ...       ...
 2015-01-08 15:56:00-05:00  0.000141 -0.000539 -0.000437 -0.000190 -0.000579
 2015-01-08 15:57:00-05:00  0.000422  0.000285  0.001203  0.000607  0.001158
 2015-01-08 15:58:00-05:00  0.000141 -0.000539  0.000000 -0.000265  0.000578
 2015-01-08 15:59:00-05:00 -0.000141 -0.000285 -0.000328 -0.000303 -0.000578
 2015-01-08 16:00:00-05:00  0.000492  0.000317  0.000437  0.000304  0.000000

                             BIIB.OQ  ...     TWX.N     UNH.N     UNP.N  \
 timestamp                            ...
 2015-01-08 09:32:00-05:00 -0.000321  ...  0.000414  0.000049  0.000000
 2015-01-08 09:33:00-05:00 -0.003420  ...  0.000296  0.000736 -0.002668
 2015-01-08 09:34:00-05:00 -0.007803  ... -0.000355  0.004168  0.000614
 2015-01-08 09:35:00-05:00 -0.013384  ...  0.000178  0.000928  0.001884
 2015-01-08 09:36:00-05:00  0.006368  ...  0.000177  0.000488 -0.003937
 ...                             ...  ...       ...       ...       ...
 2015-01-08 15:56:00-05:00 -0.000556  ... -0.000468 -0.000287 -0.000770
 2015-01-08 15:57:00-05:00  0.001127  ...  0.000176  0.001147  0.000514
 2015-01-08 15:58:00-05:00 -0.001396  ... -0.000176 -0.000477 -0.000086
 2015-01-08 15:59:00-05:00 -0.000742  ...  0.000059 -0.000621  0.000471
 2015-01-08 16:00:00-05:00  0.000071  ...  0.000527  0.000669  0.001069

                               UPS.N     USB.N     UTX.N       V.N      VZ.N  \
 timestamp
 2015-01-08 09:32:00-05:00  0.000000  0.002621  0.000000  0.002414  0.000216
 2015-01-08 09:33:00-05:00  0.000000 -0.000341  0.000000 -0.000209 -0.002158

In [6]:
first_n_days = 573
daily_top = ocp.ocp_run_all_days_fast(
    daily_matrices=daily_matrices,
    daily_pairs=daily_pairs,
    top_k=10,
    keep_top_pairs=None,
    max_lag=50,       
    band=10,          
    first_n_days=first_n_days
)

daily_top.to_parquet(f"data/top_pairs/daily_top_pairs_{first_n_days}.parquet", index=False)

 45%|████▌     | 255/565 [03:35<05:09,  1.00it/s]c:\Users\wahid\anaconda3\envs\ADA\Lib\site-packages\numpy\_core\_methods.py:190: RuntimeWarning: invalid value encountered in subtract
  x = asanyarray(arr - arrmean)
c:\Users\wahid\Desktop\FBD\OCP-StatArb-SP100\src\ocp.py:494: RuntimeWarning: invalid value encountered in subtract
  return (z - mu) / (s + 1e-12)
 71%|███████   | 400/565 [05:44<02:11,  1.26it/s]c:\Users\wahid\anaconda3\envs\ADA\Lib\site-packages\numpy\_core\_methods.py:190: RuntimeWarning: invalid value encountered in subtract
  x = asanyarray(arr - arrmean)
c:\Users\wahid\Desktop\FBD\OCP-StatArb-SP100\src\ocp.py:494: RuntimeWarning: invalid value encountered in subtract
  return (z - mu) / (s + 1e-12)
 80%|████████  | 454/565 [06:30<01:34,  1.18it/s]c:\Users\wahid\anaconda3\envs\ADA\Lib\site-packages\numpy\_core\_methods.py:190: RuntimeWarning: invalid value encountered in subtract
  x = asanyarray(arr - arrmean)
c:\Users\wahid\Desktop\FBD\OCP-StatArb-SP100\src\ocp.py:494: RuntimeWarning: invalid value encountered in subtract
  return (z - mu) / (s + 1e-12)
100%|██████████| 565/565 [07:57<00:00,  1.18it/s]

In [7]:
daily_top = pd.read_parquet(f"data/top_pairs/daily_top_pairs_573.parquet")

daily_top

            date leader follower     l_hat   sigma_l        cost
0     2015-01-02  HON.N      V.N  1.010965  1.614725  201.883981
1     2015-01-02  WFC.N     KO.N  1.129870  1.680167  210.109826
2     2015-01-02  ALL.N     KO.N  1.121739  1.862200  208.889776
3     2015-01-02  UNP.N    NEE.N  1.025424  1.925352  218.139694
4     2015-01-02  MMM.N     GD.N  1.043860  1.941650  200.560815
...          ...    ...      ...       ...       ...         ...
5645  2017-03-31  BAC.N    WFC.N  1.009070  2.429955  171.826367
5646  2017-03-31  JPM.N      V.N  1.184486  2.434795  219.740487
5647  2017-03-31  EMR.N    WFC.N  1.612903  2.464510  212.564136
5648  2017-03-31  AIG.N     MS.N  1.183158  2.511894  207.897267
5649  2017-03-31   PG.N    SPY.P  2.246862  2.555194  220.654192

[5650 rows x 6 columns]

In [34]:
PAIRS_PATH = Path("data/top_pairs/daily_top_pairs_573_90.parquet")
RETURNS_DIR = Path("data/selected/SP100/bbo")
INDEX_TICKER = "SPY.P"

params = OCPTradeParams(
    lookback=20,
    k=2.5,
    tc_bps=2.0,
    r_bps=4.0,
    max_lag_minutes=30,
    ci_z=2.8,
    enter_on_next_bar=True,
)

In [35]:
results = run_backtest(
    pairs_path=PAIRS_PATH,
    returns_dir=RETURNS_DIR,
    index_ticker=INDEX_TICKER,
    params=params,
)

In [36]:
results

shape: (572, 5)
┌────────────┬───────────┬────────────┬─────────┬───────┐
│ trade_day  ┆ daily_pnl ┆ pairs_used ┆ entries ┆ exits │
│ ---        ┆ ---       ┆ ---        ┆ ---     ┆ ---   │
│ date       ┆ f64       ┆ i64        ┆ i64     ┆ i64   │
╞════════════╪═══════════╪════════════╪═════════╪═══════╡
│ 2015-01-05 ┆ 0.000554  ┆ 5          ┆ 20      ┆ 20    │
│ 2015-01-06 ┆ -0.016512 ┆ 8          ┆ 36      ┆ 36    │
│ 2015-01-07 ┆ -0.005762 ┆ 4          ┆ 13      ┆ 13    │
│ 2015-01-08 ┆ 0.001664  ┆ 5          ┆ 26      ┆ 26    │
│ 2015-01-09 ┆ 0.000025  ┆ 2          ┆ 8       ┆ 8     │
│ …          ┆ …         ┆ …          ┆ …       ┆ …     │
│ 2017-04-06 ┆ 0.0       ┆ 0          ┆ 0       ┆ 0     │
│ 2017-04-07 ┆ 0.0       ┆ 0          ┆ 0       ┆ 0     │
│ 2017-04-10 ┆ 0.0       ┆ 0          ┆ 0       ┆ 0     │
│ 2017-04-11 ┆ 0.0       ┆ 0          ┆ 0       ┆ 0     │
│ 2017-04-12 ┆ 0.0       ┆ 0          ┆ 0       ┆ 0     │
└────────────┴───────────┴────────────┴─────────┴───────┘

In [37]:
daily = results["daily_pnl"].to_numpy()
mu = daily.mean()
sigma = daily.std(ddof=0)
sharpe = (mu / sigma) * np.sqrt(252) if sigma > 0 else np.nan
print("Approx Sharpe:", sharpe)
print("Total PnL:", daily.sum())
print("Mean Daily PnL:", mu)

Approx Sharpe: 0.11441079053377863
Total PnL: 0.3446949276750766
Mean Daily PnL: 0.0006026135099214626

In [31]:
df = results.to_pandas()